### ISSUE TITLE
versions are ignored because they are not tagged

### ISSUE THREAD

**Issue by Mipsters** [ETLCPP/etl-arduino#4]
Part of Arduino's [requirements from libraries](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-a-library-to-be-added-to-library-manager) are that:

> The library repository must have a [Git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) (or [release](https://docs.github.com/repositories/releasing-projects-on-github/managing-releases-in-a-repository)) and must have been compliant with all the above requirements at the time of that tag.

so sadly, all the update commits in this repository did not translate to available version in Arduino's Library Manager

**Comment by zabuxx** [comment]
The [ETL entry in the Arduino libraries](https://www.arduino.cc/reference/en/libraries/embedded-template-library-etl/) has not been updated since 20.22.0

It is not picked up by the library indexer, with the reason given [here](https://downloads.arduino.cc/libraries/logs/github.com/ETLCPP/etl-arduino/)

It's an incorrect naming in the _library.properties_ (and _library.json_):

`name=Embedded Template Library - Arduino`

should be:

`name=Embedded Template Library ETL`

Would be great to get access to the latest features of this magnificent library! Thanks!

**Comment by Mipsters** [comment]
@zabuxx I fixed this issue in an already merged PR
it's not displayed in Arduino's logs yet because of the issue I describe here
We just need a tag for the fix to apply 🥲

**Comment by jwellbelove** [comment]
I accepted the pull-request, but it seems the sync with the main line ETL reverted it back again.

**Comment by jwellbelove** [comment]
I've corrected the library name and re-tagged 20.28.10

**Comment by Mipsters** [comment]
@jwellbelove you tagged a commit without the pr with the fixes, it's name is still wrong

the tag 20.38.10 currently points to the commit [f3c6a31](https://github.com/ETLCPP/etl-arduino/commit/f3c6a311e58d3e9e548d7b2b38b15e41aad118e4)
the name fixes are in the commit [3610df1](https://github.com/ETLCPP/etl-arduino/commit/3610df197cd3cdbdb1c687e1674a9a3c247d21a2) (master)

**Comment by jwellbelove** [comment]
I remade the changes on GitHub and committed them directly to master, deleted the old tag, and then recreated the tag for master.

**Comment by Mipsters** [comment]
The issue seems to persist, and when I check in GitHub the tag still seems to be on the wrong commit hash

And another thing, I think there may be a redundant "-" in the name in the `.properties` file
Even if the tag will be on the correct commit, it still won't work because of this

Sorry it takes so long, it seems to be really specific

**Comment by zabuxx** [comment]
Hi, from the [output of the library indexer](https://downloads.arduino.cc/libraries/logs/github.com/ETLCPP/etl-arduino/) it seems this issue persists because in `library.properties` the line

    name=Embedded Template Library ETL

is needed instead of the current

    name=Embedded Template Library - ETL

Could you change this for a next release? (I assume this value gets pushed from the main ETLCPP/etl repo)

Thanks

**Comment by zabuxx** [comment]
Yes!! ETL 20.38.11 has been added to the [Arduino Library](https://www.arduino.cc/reference/en/libraries/embedded-template-library-etl/)   !!

**Thanks a lot!!**

**Comment by Mipsters** [comment]
Thank you so much!
